#!/usr/bin/env python3
"""Find a stash or a commit in a git repo

Usage:
  findmystash <word_to_find> [--reflogs] [--diff]

Options:
  --diff          Print the diff
  --reflogs       Search in reflogs and not stashes
  --version       Show version.
"""

import re
import sys
import subprocess
import argparse

def get_command(reflogs, i):
    if reflogs:
        c = "git show HEAD@{%d}"
    else:
        c = "git stash show -u stash@{%i}"

    return c % i

def main(options):
    i = 0

    while True:
        c = get_command(options.reflogs, i)
        try:
            res = subprocess.check_output(c.split(" "))
        except subprocess.CalledProcessError as e:
            if i > 0:
                print("Got exception: %s" % e)
                return
            raise e

        if re.findall(options.regex[0], str(res)):
            print("\r%s contain %s" % (c.split(" ")[-1], options.regex[0]))
        if options.diff:
            print("\r%s\n\n" % res.decode())
        i += 1


if __name__ == '__main__':
    PARSER = argparse.ArgumentParser()
    PARSER.add_argument('--reflogs', default=False, action="store_true")
    PARSER.add_argument('--diff', default=False, action="store_true")
    PARSER.add_argument('regex', nargs=1)
    options = PARSER.parse_args()
    main(options)
