#!/usr/bin/env python3

import os
import time
import shutil
import subprocess
import sys

mkdump_path = os.path.expanduser("~/.cache/gstmkdump")
shutil.rmtree(mkdump_path, ignore_errors=True)
os.makedirs(mkdump_path)

print(f"Dumping GStreamer pipelines into {mkdump_path}")
os.environ["GST_DEBUG_DUMP_DOT_DIR"] = mkdump_path

try:
    subprocess.check_call(sys.argv[1:])
except:
    time.sleep(1.0)

